# Generated by Django 3.1.4 on 2020-12-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='fillvalue',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
